# Description: Server configuration for the project (excluding database)
#              It runs on Ubuntu, so do what you like below.
#
# NOTE: YOU PROBABLY DON'T HAVE TO MODIFY THIS FILE MUCH
#
# Company: Speko Technologies
# Author: Spencer kotowick

FROM mysql
